language: node_js
node_js:
  - "4.3.2"
install: npm run root:install:all
script: printenv && npm run test && npm run lint
#deploy:
#  - provider: script # TODO
#    script: npm run root:deploy:all # ci
#  - provider: script
#    script: npm run root:integration:all
#  - provider: script
#    script: npm run root:deploy:all # demo
